"""empty message

Revision ID: 053f5b036092
Revises: 9617662d19bc
Create Date: 2021-08-28 21:52:37.918459

"""
from alembic import op
import sqlalchemy as sa
from getpass import getpass
from app.models import Usuarios
from app import db


# revision identifiers, used by Alembic.
revision = '053f5b036092'
down_revision = '9617662d19bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('nome', sa.String(length=100), nullable=False),
                    sa.Column('email', sa.String(length=200), nullable=False),
                    sa.Column('_Usuarios__senha', sa.String(length=128), nullable=False),
                    sa.Column('admin', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('nome')
                    )
    # ### end Alembic commands ###
    print('==== Criação do usuário administrador ===')
    nome = input('Nome: ')
    email = input('E-mail: ')
    senha = getpass('Senha: ')
    admin = Usuarios()
    admin.nome = nome
    admin.email = email
    admin.senha = senha
    db.session.add(admin)
    db.session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
