"""empty message

Revision ID: 9617662d19bc
Revises: 
Create Date: 2021-08-08 11:13:45.155495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9617662d19bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('garantia', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('preco', sa.String(length=20), nullable=True),
    sa.Column('img_principal', sa.String(length=300), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('hds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=True),
    sa.Column('interface', sa.String(length=20), nullable=True),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('cache', sa.Integer(), nullable=True),
    sa.Column('formato', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagens_produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caminho', sa.String(length=300), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nucleos', sa.Integer(), nullable=True),
    sa.Column('threads', sa.Integer(), nullable=True),
    sa.Column('frequencia_base', sa.Integer(), nullable=True),
    sa.Column('frequencia_turbo', sa.Integer(), nullable=True),
    sa.Column('tdp', sa.Integer(), nullable=True),
    sa.Column('soquete', sa.String(length=20), nullable=True),
    sa.Column('litografia', sa.String(length=20), nullable=True),
    sa.Column('tecnologias', sa.LargeBinary(), nullable=True),
    sa.Column('video', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processadores')
    op.drop_table('imagens_produtos')
    op.drop_table('hds')
    op.drop_table('produtos')
    # ### end Alembic commands ###
